### Handling responses in the HTTP Client
### https://blog.jetbrains.com/phpstorm/2018/04/handling-reponses-in-the-http-client

### API

GET {{graphql_endpoint}}?query={version}

###

GET {{graphql_endpoint}}?query={reset}

### USER

GET {{graphql_endpoint}}?query={me {id name email status imageUrl}}
x-token: {{token}}

> {%
  client.assert(response.status === 200, "Status: " + response.status);

  client.global.set("userId", response.body.data.me.id);
%}

###

GET {{graphql_endpoint}}?query={user(id: "33e374ef-cd3f-4899-a22f-e4fa28adff11") {id name status}}

### AUTHENTICATION

POST {{graphql_endpoint}}
Content-Type: application/json

{
  "query": "mutation {checkEmail(email: \"user@dummy.com\") {isAvailable isBlacklisted}}"
}

###

POST {{graphql_endpoint}}
Content-Type: application/json

{
  "query": "mutation {resendEmailConfirmation(email: \"dgomez@orangeloops.com\") {_}}"
}

###

POST {{graphql_endpoint}}
Content-Type: application/json

{
  "query": "mutation {signUp(name: \"Daniel\", email: \"dgomez@orangeloops.com\", password: \"Password01\") {_}}"
}

###

POST {{graphql_endpoint}}
Content-Type: application/json

{
  "query": "mutation {confirmEmail(token: \"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiYzU3N2ZkMTEtMjYwNS00MGM2LTgwZjMtYzcyNmVmOTdlNzU1IiwiZW1haWwiOiJkZ29tZXpAb3JhbmdlbG9vcHMuY29tIiwiY29kZSI6IkRJOFFEQ0YzTkdwWmxuOU1ULW13MnEifSwiaWF0IjoxNTU2ODI2NTQyLCJleHAiOjE1NTY5MTI5NDJ9.qAKCoaI6kXpkq_iUdQlrXJfMZoVdR7xTuPa56-JC2qs\") {_}}"
}

###

POST {{graphql_endpoint}}
Content-Type: application/json

{
  "query": "mutation {signIn(email: \"dgomez@orangeloops.com\", password: \"Password01\", generateRefreshToken: true) {token refreshToken}}"
}

> {%
  client.assert(response.status === 200, "Status: " + response.status);

  client.global.set("token", response.body.data.signIn.token);
  client.global.set("refreshToken", response.body.data.signIn.refreshToken);
%}

###

POST {{graphql_endpoint}}
Content-Type: application/json

{
  "query": "mutation {refreshTokens(token: \"{{refreshToken}}\") {token refreshToken}}"
}

> {%
  client.assert(response.status === 200, "Status: " + response.status);

  client.global.set("token", response.body.data.refreshTokens.token);
  client.global.set("refreshToken", response.body.data.refreshTokens.refreshToken);
%}

###

POST {{graphql_endpoint}}
Content-Type: application/json

{
  "query": "mutation {requestResetPassword(email: \"dgomez@orangeloops.com\") {_}}"
}

###

POST {{graphql_endpoint}}
Content-Type: application/json

{
  "query": "mutation {resetPassword(token: \"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRnb21lekBvcmFuZ2Vsb29wcy5jb20iLCJjb2RlIjoiQkM1R2dZTHR4SG9iQXJiX2VLMkRTXyIsImlhdCI6MTU0Nzc1MDUwNywiZXhwIjoxNTQ3ODM2OTA3fQ.UyrjtCwhtmAstOrDGrd1OnYSyjHeCQ2oq2cWUAMSNzI\" password: \"Password02\") {_}}"
}

### USER

POST {{graphql_endpoint}}
Content-Type: application/json
x-token: {{token}}

{
  "query": "mutation {updateUser(id: \"f9d4ac73-9756-4e20-8c70-fead0c588814\" name: \"Update user test\") {id name}}"
}

###

POST {{graphql_endpoint}}
Content-Type: application/json
x-token: {{token}}

{
  "query": "mutation {deleteUser(id: \"d087c5d5-1e8e-4eb0-8ea8-372655851d1f\")}"
}